name: Update Repository
on:
  repository_dispatch:
    types: [trigger-update]

jobs:
  update-repository:
    name: Update Repository
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: "^3.8.0"

    - name: Update Repository
      run: tools/update-repository.sh
      env:
        GITHUBTOKEN: ${{ github.token }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ github.token }}
        commit-message: update repository
        title: Updated Repository
        body: |
          Automatically updated the repository to include the latest versions.
